[features]
seeds = false
[programs.localnet]
solana_twitter = "7EcsqgQGnKTsFLjp2PFZ8hzChxXBDoVApUzEKamcQABE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/lamida/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
